"""마크다운 체크리스트 생성 모듈.

분석 결과를 GitHub PR 코멘트용 마크다운 포맷으로 변환한다.
"""

from .risk_analyzer import AnalysisResult
from .rules import RiskLevel

# Bot 코멘트 식별 시그니처
BOT_SIGNATURE = "<!-- pr-review-checker-bot -->"

RISK_EMOJI = {
    RiskLevel.HIGH: "🔴",
    RiskLevel.MEDIUM: "🟡",
    RiskLevel.LOW: "🟢",
}

RISK_LABEL_EMOJI = {
    "HIGH": "⚠️",
    "MEDIUM": "⚡",
    "LOW": "ℹ️",
}

CATEGORY_EMOJI = {
    "Security Group": "🔒",
    "EKS Nodegroup": "☸️",
    "IAM": "🔑",
    "Network": "🌐",
    "Other": "📋",
}


def generate_checklist(result: AnalysisResult) -> str:
    """분석 결과를 마크다운 체크리스트로 변환한다."""
    lines: list[str] = []

    lines.append(BOT_SIGNATURE)
    lines.append("")
    lines.append("## 🔍 Terraform PR Review Checklist")
    lines.append("")

    risk_emoji = RISK_EMOJI[result.overall_risk]
    lines.append(f"**Overall Risk Level: {risk_emoji} {result.overall_risk.value}**")
    lines.append(f"**Required Approvers: {result.required_approvers}**")

    lifecycles_str = ", ".join(sorted(result.lifecycles)) if result.lifecycles else "N/A"
    lines.append(f"**Changed Lifecycles: {lifecycles_str}**")

    env_str = ", ".join(sorted(result.environments)) if result.environments else "N/A"
    lines.append(f"**Target Environment: {env_str}**")

    lines.append(f"**Terraform Files Changed: {result.total_tf_files}**")
    lines.append("")

    if result.findings:
        categories = result.findings_by_category
        for category in sorted(categories.keys()):
            findings = categories[category]
            emoji = CATEGORY_EMOJI.get(category, "📋")
            lines.append(f"### {emoji} {category} Changes")
            lines.append("")

            for finding in sorted(findings, key=lambda f: f.risk_level, reverse=True):
                risk_label = RISK_LABEL_EMOJI.get(finding.risk_level.value, "")
                location = f"({finding.file_path}"
                if finding.line_number > 0:
                    location += f":{finding.line_number}"
                location += ")"
                lines.append(
                    f"- [ ] {risk_label} **{finding.risk_level.value}**: "
                    f"{finding.message} {location}"
                )
            lines.append("")
    else:
        lines.append("### ✅ No risk findings detected")
        lines.append("")
        lines.append("This PR appears to have low-risk changes.")
        lines.append("")

    # Summary Table
    lines.append("### 📊 Summary Table")
    lines.append("")
    lines.append("| Category | HIGH | MEDIUM | LOW |")
    lines.append("|----------|------|--------|-----|")

    if result.findings:
        categories = result.findings_by_category
        for category in sorted(categories.keys()):
            findings = categories[category]
            high = sum(1 for f in findings if f.risk_level == RiskLevel.HIGH)
            medium = sum(1 for f in findings if f.risk_level == RiskLevel.MEDIUM)
            low = sum(1 for f in findings if f.risk_level == RiskLevel.LOW)
            lines.append(f"| {category} | {high} | {medium} | {low} |")
    else:
        lines.append("| (none) | 0 | 0 | 0 |")

    counts = result.risk_counts
    lines.append(
        f"| **Total** | **{counts['HIGH']}** "
        f"| **{counts['MEDIUM']}** | **{counts['LOW']}** |"
    )
    lines.append("")
    lines.append("---")
    lines.append("*Generated by PR Review Checker Bot* 🤖")
    lines.append("")

    return "\n".join(lines)
