name: Terraform Plan

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "**/*.tf"
      - "**/*.tfvars"

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, stg, prod]
        lifecycle: [network, eks-cluster]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Check if directory has changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            terraform:
              - 'live/${{ matrix.environment }}/${{ matrix.lifecycle }}/**'
              - 'modules/**'

      - name: Terraform Init
        if: steps.changes.outputs.terraform == 'true'
        run: terraform init -backend=false
        working-directory: live/${{ matrix.environment }}/${{ matrix.lifecycle }}/

      - name: Terraform Validate
        if: steps.changes.outputs.terraform == 'true'
        run: terraform validate
        working-directory: live/${{ matrix.environment }}/${{ matrix.lifecycle }}/
